### ISSUE TITLE
playground emits warnings after automatic-memory-managment merge

### ISSUE THREAD

**Issue by schnepe2** [qooxdoo/qooxdoo#9186] opened 2016-09-22 16:14 UTC
The current 'development' [playground](http://www.qooxdoo.org/devel/playground/#Hello%20World-ria) spits out warnings (just open the log)
It seems that the `toHtml` method of `qx.log.appender.Util` is using `qx.core.ObjectRegistry.fromHashCode` (without first checking for `qx.core.ObjectRegistry.hasHashCode` e.g.)
...which is not good after PR #8986 

![issue-warnings](https://cloud.githubusercontent.com/assets/18400313/18756455/4641c630-80f0-11e6-904e-a29ec42aa23b.png)

**Comment by cajus** [comment] 2016-09-22 18:02
The framework tests output many of these messages, too. Should be inspected...

**Comment by level420** [comment] 2016-09-23 06:17
Also in the testrunner. @johnspackman would you please have a look into? Thank you.

**Comment by level420** [comment] 2016-09-26 07:16
This seems to be caused by ```qx.log.appender.Util.toHtml``` used in ```qx.log.appender.Element``` ( https://github.com/qooxdoo/qooxdoo/blob/master/framework/source/class/qx/log/appender/Util.js#L41 ) when logging into an dom element as used in the testrunner and the playgrouground.

It's not a bug per se, but the call to ```qx.core.ObjectRegistry.fromHashCode``` is missing the second parameter ```suppressWarnings``` which has to be set to ```true``` in this case.

I'll create a PR.

**Comment by level420** [comment] 2016-09-27 13:41
Fixed via https://github.com/qooxdoo/qooxdoo/pull/9191
Thank you @schnepe2 for reporting!

**Closed by level420** 2016-09-27 13:41 UTC
Labels: bug, bug confirmed, C:app.playground, C:app.testrunner
