### ISSUE TITLE
Firefox 49 doesn't like qx.lang.String.stripScripts anymore

### ISSUE THREAD

**Issue by petitben** [qooxdoo/qooxdoo#9196] opened 2016-09-29 22:42 UTC
Hi guys,

Quite strange! I noticed some of my qx-powered apps don't run anymore with the fresh Firefox 49.
It randomly (but nearly always) produces a js error : "SyntaxError: invalid regular expression flag j".

After some deep analysis it looks like this line (in qx.lang.String.stripScripts) is the guilty:
`var text = str.replace(/<script[^>]*>([\s\S]*?)<\/script>/gi, function()
      {
        scripts += arguments[1] + '\n';
        return "";
      });`

To be honest I don't see anything strange in that js declaration. 
At first sight I thought it was maybe because of my antivirus software... too way aggressive but disabling it didn't fix it.

However after replacing the code by:
`var scrRexp = new RegExp('<script[^>]*>([\\s\\S]*?)</script>','gi');
      var text = str.replace(scrRexp, function()
      {
        scripts += arguments[1] + '\n';
        return "";
      });`
I started to work again.

I noticed that some JS functions related to String replacements have been updated in FF49: https://developer.mozilla.org/en-US/Firefox/Releases/49

I don't know if it's a regression at Mozilla side...

Thoughts ?

**Comment by level420** [comment] 2016-09-30 06:36
@petiben Thank you for your issue report.

I've had a look into the entries in the firefox 49 changelog. There are two changes which are related to regular expressions and strings:

1. Some ES6 related changes regarding ```RegExp``` ( https://bugzilla.mozilla.org/show_bug.cgi?id=887016 )
2. The deprecation of a non standard flag argumnt in ```String.prototype.match/search/replace``` ( https://bugzilla.mozilla.org/show_bug.cgi?id=1108382 )

I don't think one of them causes "per se" the issue, but of course it could be a bug in firefox.

@petitben it would be very helpful to have a string which is causing the issue in your app so we are able to reproduce it. We would then also add this string or a similar string causing the issue to the testrunner tests, so the issue should pop up if other browsers have similar problems. Thank you.

**Comment by level420** [comment] 2016-10-05 06:10
@petitben would be nice if you find the time to send us a test case which triggers the bug. Without that we are not able to reproduce the problem. Thank you!

**Comment by petitben** [comment] 2016-10-05 07:19
@level420 Don't worry I'll provide it as soon as possible... The fact is I am really too busy this week. Stay tuned :-)

**Comment by level420** [comment] 2016-10-05 07:41
@petiben OK. No problem :smile:

**Comment by level420** [comment] 2016-12-02 07:20
@petitben closing this for now. If you find some time to create a testcase, feel free to reopen.

**Closed by level420** 2016-12-02 07:20 UTC
Labels: P:Firefox
