### ISSUE TITLE
Enhance Property definition with "comparator"

### ISSUE THREAD

**Issue by schnepe2** [qooxdoo/qooxdoo#9039] opened 2016-06-08 19:40 UTC
Extension of the property definitions to be able to "override" the equality-check of the generated property setters.

```
  properties :
  {
    value : {
      check    : "Integer",
      nullable : true,
      init     : null,
      event    : "changeValue",
      compare  : function (a, b) { return Object.is(a, b); } // <= instead of regular "a===b"
    }
  }

```

One rationale for this feature request is to be able to create a (numeric) property that can distinguish between zero (0) and minus-zero (-0) ...and is asked here:
http://stackoverflow.com/questions/37681623/qooxdoo-enhance-property-to-distinguish-0-from-0

**Comment by level420** [comment] 2016-06-09 06:56
@schnepe2 as I read from the stackoverflow post you already have some code which hooks into property creation in qx.core.Property. Please share your code so we can have a look into. Thank you.

**Comment by oetiker** [comment] 2016-06-09 07:03
I would call it something else than 'compare' since it has the purpose of detecting value change ...but I like the idea ... it could also be used to make the property less sensitive to value change instead of more sensitive ...

**Comment by level420** [comment] 2016-06-09 07:16
...then maybe comparator?

**Comment by johnspackman** [comment] 2016-06-09 07:40
👍  for comparator

@schnepe2 FWIW you might like to consider the transform feature of properties - it would allow you to normalise -0 into 0 so that your example would work, although obviously that only works if you don't care about -0.

As a general case for properties, could we change the default implementation of comparator for Integers to consider -0 and 0 as the same?  It seems pretty dumb to me that there is this kind of distinction, as it is an artifact of implementation and not something arithmetic.  

It's the sort of thing that I could imagine spending hours trying to reproduce a bug caused by this (even the code `+0 === -0` returns true), and I can't imagine that there are many situations where someone would *want* -0 to be distinct.

**Comment by schnepe2** [comment] 2016-06-09 07:44
I've done several approaches to this 'issue'/'feature':

1. Brutal search & replace in qx.core.Property
    (changing the framework source!)

2. Configurable option in qx.core.Property
    (still a change of the framework source needed!)
    See attachments for the changes. I've deliberately called the config option
    "foobar" to indicate that this is *not* my favorite choice ;)

3. Runtime search & replace in defer method
    (a bit nicer since no framework change needed, but still feels ugly)
    See attachments 2 & 3 (for usage example)


That's all I've got so far.
The feature request however asked for a bit more general approach by defining a 
"comperator" function instead (we can argue about the name ;) )

/Peter


Am 09.06.2016 um 08:56 schrieb Dietrich Streifert:
> @schnepe2 <https://github.com/schnepe2> as I read from the stackoverflow post
> you already have some code which hooks into property creation in
> qx.core.Property. Please share your code so we can have a look into. Thank you.

Index: Property.js
===================================================================
--- Property.js	(revision 7861)
+++ Property.js	(working copy)
@@ -273,6 +273,8 @@
       transform    : "string",   // String
       deferredInit : "boolean",  // Boolean
       validate     : null        // String, Function
+      ,
+      fooBar       : "boolean"   // Boolean
     },
 
 
@@ -820,7 +822,7 @@
       }
 
       if (hasCallback) {
-        this.__emitOldNewComparison(code, incomingValue, store, variant);
+        this.__emitOldNewComparison(code, config, incomingValue, store, variant);
       }
 
       if (config.inheritable) {
@@ -978,11 +980,12 @@
      * Emit code, which returns if the incoming value equals the current value.
      *
      * @param code {String[]} String array to append the code to
+     * @param config {Object} The property configuration map
      * @param incomingValue {Boolean} Whether the setter has an incoming value
      * @param store {Object} The data store to use for the incoming value
      * @param variant {String} Method variant.
      */
-    __emitOldNewComparison : function(code, incomingValue, store, variant)
+    __emitOldNewComparison : function(code, config, incomingValue, store, variant)
     {
       var resetValue = (
         variant === "reset" ||
@@ -990,8 +993,13 @@
         variant === "resetRuntime"
       );
 
-      if (incomingValue) {
-        code.push('if(this.', store, '===value)return value;');
+      if (incomingValue)
+      {
+        if (config.foobar) {
+          code.push('if(Object.is(this.', store, ',value))return value;');
+        } else {
+          code.push('if(this.', store, '===value)return value;');
+        }
       } else if (resetValue) {
         code.push('if(this.', store, '===undefined)return;');
       }
@@ -1427,7 +1435,11 @@
       code.push('}');
 
       // Compare old/new computed value
-      code.push('if(old===computed)return value;');
+      if (config.foobar) {
+        code.push('if(Object.is(old,computed))return value;');
+      } else {
+        code.push('if(old===computed)return value;');
+      }
 
       // Note: At this point computed can be "inherit" or "undefined".
 
@@ -1474,7 +1486,11 @@
       }
 
       // Compare old/new computed value
-      code.push('if(old===computed)return value;');
+      if (config.foobar) {
+        code.push('if(Object.is(old,computed))return value;');
+      } else {
+        code.push('if(old===computed)return value;');
+      }
 
       // Normalize old value
       if (config.init !== undefined && variant !== "init") {

**Comment by johnspackman** [comment] 2016-06-09 07:52
@schnepe2 please can you provide this as a pull request?

**Comment by schnepe2** [comment] 2016-06-09 07:53
No, sorry

**Comment by level420** [comment] 2016-06-09 07:53
@schnepe2 this does not look to far away from a pull request ;-) computed could be a string holding the comparison javascript code. In your example "Object.is(old,computed)"

**Comment by schnepe2** [comment] 2016-06-09 08:02
I know it's not far away...but currently only usable for *me*
I would really love to see this being more usable to others as well ;)

- config-key: "comparator" (as @level420 proposed)
- config-type: "string" or "function" (returning {Boolean})
- default: as is (=== operator)

@johnspackman : The "work-around" using the transformation does not really cut the mustard.
The firing of events and calling of 'apply' methods is not consistent when the internal comparison still treats `+0` as equal to `-0`...
I would rather then use a complete "manual" implementation of `setXX`, `getXXX`, `resetXXX`, ...

**Comment by schnepe2** [comment] 2016-06-09 08:07
> this does not look to far away from a pull request ;-) computed could be a string holding the comparison javascript code. In your example "Object.is(old,computed)"
Yeah, but the variable names used are different throughout the setter-code:

- `if(this.$$???)===value)`
- `if(old===computed)`
- `if(computed===inherit)`

**Comment by level420** [comment] 2016-06-09 08:10
Yes, but it can be encapsulated in a function which itself contains the comparison.

**Comment by johnspackman** [comment] 2016-06-09 08:25
re the "transform" function - if your transform method detects -0 and then returns +0 then it will work as I described because the comparision code will never see -0, only +0.

However, please can you provide a playground example which illustrates your problem?  I've just done this one: http://tinyurl.com/j7duc7b and it only shows one change event; someone on SO has just raised the same question.

**Comment by johnspackman** [comment] 2016-06-09 08:27
ah sorry, i've just seen that you *want* to distinguish +0 from -0, my mistake

**Comment by schnepe2** [comment] 2016-06-09 08:33
>  [...]someone on SO has just raised the same question[...]

That "someone" might have been me ;)

Here some test-case proposals (untested of course):
```
qx.Class.define("qx.test.core.Property",
{
  extend : qx.dev.unit.TestCase,

  members :
  {

    testComperatorFunction : function()
    {
      qx.Class.define("qx.TestProperty",
      {
        extend : qx.core.Object,
        properties : {
          prop : {
            check   : "Number",
            init : null,
            nullable: true,
            event   : "changeProp",
            comperator : function (a,b) { return Object.is(a, b); }
          }
        }
      });

      var object = new qx.TestProperty();
      object.setProp(0);


      // check for the event
      var self = this;
      this.assertEventFired(object, "changeProp", function () {
        object.setProp(-0);
      }, function (e) {
        var isNegativeZero = this.__isNegativeZero( e.getData() );
        var isPositiveZero = this.__ispositiveZero( e.getOldData() );
        self.assertTrue(isNegativeZero, "Wrong data in the event!");
        self.assertTrue(isPositiveZero, "Wrong old data in the event!");
      }, "Change event not fired!");

      object.dispose();
    },


    testComperatorString : function()
    {
      qx.Class.define("qx.TestProperty",
      {
        extend : qx.core.Object,
        properties : {
          prop : {
            check   : "Number",
            init : null,
            nullable: true,
            event   : "changeProp",
            comperator : "Object.is(a, b)"
          }
        }
      });

      var object = new qx.TestProperty();
      object.setProp(0);


      // check for the event
      var self = this;
      this.assertEventFired(object, "changeProp", function () {
        object.setProp(-0);
      }, function (e) {
        var isNegativeZero = this.__isNegativeZero( e.getData() );
        var isPositiveZero = this.__ispositiveZero( e.getOldData() );
        self.assertTrue(isNegativeZero, "Wrong data in the event!");
        self.assertTrue(isPositiveZero, "Wrong old data in the event!");
      }, "Change event not fired!");

      object.dispose();
    },


    __isNegativeZero : function (value) {
      return value===0 && (1/value < 0); // 1/-0 => NegativeInfinity
    },


    __ispositiveZero : function (value) {
      return value===0 && (1/value >= 0); // 1/+0 => PositiveInfinity
    },
   //...
```

**Comment by level420** [comment] 2016-06-09 09:21
some code idea:

```javascript
          if (typeof config.comparator === "function")
          {
            code.push('if(',clazz.classname, '.$$properties.', name);
            code.push('.comparator.call(this, this.', store, ', value)) return value;');
          }
          else if (typeof config.comparator === "string")
          {
            code.push(' if(function(old, computed) { return (', config.comparator, ')?true:false; }).call(this, this.', store, ', value)) return value;')
          }
		  else {
			code.push('if(this.', store, '===value)return value;');
		  }
```

**Comment by oetiker** [comment] 2016-06-09 09:39
can the attribute be:

`changeDetector: function(a,b){... return true or false}`

then if no changeDetector is set for a property, we use function(a,b){return a === b}

**Comment by schnepe2** [comment] 2016-06-09 09:51
@level420 thanks for the code idea!
Here's my current (working) patch for `qx.core.Property` :
@oetiker my patch still uses "`comparator`" as attribute, but "`changeDetector`" is also not a bad name ;)
```
Index: Property.js
===================================================================
--- Property.js	(revision 7861)
+++ Property.js	(working copy)
@@ -272,7 +272,8 @@
       check        : null,       // Array, String, Function
       transform    : "string",   // String
       deferredInit : "boolean",  // Boolean
-      validate     : null        // String, Function
+      validate     : null,       // String, Function
+      comparator   : null        // String, Function
     },
 
 
@@ -813,6 +814,8 @@
 
       var store = this.__getStore(variant, name);
 
+      this.__emitComparatorFunction(code, clazz, config, name);
+
       this.__emitSetterPreConditions(code, config, name, variant, incomingValue);
 
       if (incomingValue) {
@@ -891,6 +894,33 @@
 
 
     /**
+     * Emit code for the equality check evaluation
+     *
+     * @param code {String[]} String array to append the code to
+     * @param clazz {Class} the class which originally defined the property
+     * @param config {Object} The property configuration map
+     * @param name {String} name of the property
+     */
+    __emitComparatorFunction : function (code, clazz, config, name)
+    {
+      code.push('function equ(a,b){');
+
+      if (typeof config.comparator === "function")
+      {
+        code.push('return !!', clazz.classname, '.$$properties.', name,
+                                               '.comparator.call(this, a,b);');
+      }
+      else if (typeof config.comparator === "string") {
+        code.push('return !!(', config.comparator, ');');
+      }
+      else {
+        code.push('return a===b;');
+      }
+      code.push('}');
+    },
+
+
+    /**
      * Emit code to check the arguments preconditions
      *
      * @param code {String[]} String array to append the code to
@@ -990,8 +1020,9 @@
         variant === "resetRuntime"
       );
 
-      if (incomingValue) {
-        code.push('if(this.', store, '===value)return value;');
+      if (incomingValue)
+      {
+        code.push('if(equ(this.', store, ',value))return value;');
       } else if (resetValue) {
         code.push('if(this.', store, '===undefined)return;');
       }
@@ -1427,7 +1458,7 @@
       code.push('}');
 
       // Compare old/new computed value
-      code.push('if(old===computed)return value;');
+      code.push('if(equ(old,computed))return value;');
 
       // Note: At this point computed can be "inherit" or "undefined".
 
@@ -1474,7 +1505,7 @@
       }
 
       // Compare old/new computed value
-      code.push('if(old===computed)return value;');
+      code.push('if(equ(old,computed))return value;');
 
       // Normalize old value
       if (config.init !== undefined && variant !== "init") { 
```

**Comment by schnepe2** [comment] 2016-06-09 09:55
Due to my inability to provide a pull-request, here's the complete file:
[Property.zip](https://github.com/qooxdoo/qooxdoo/files/306613/Property.zip)

**Comment by oetiker** [comment] 2016-06-09 11:26
@schnepe2 what is preventing you from creating a PR ? you can even edit files directly in github todo that ...

**Comment by derrell** [comment] 2016-06-09 11:40
Suggestion: If boolean functions have a name that implies (or better yet, states) the meaning of the return value, there is less confusion in using the function. The function name *changeDetector* doesn't imply the meaning of the return value. *true* could mean that a there is a change or that there is not a change (although one might surmise the former). With a small name alteration, however, it can become obvious. How about *changeDetected* which has a clear meaning if *true* is returned?

**Comment by schnepe2** [comment] 2016-06-09 11:45
@oetiker ..mostly inexperience. Secondly I currently can't access all the net (someone here has completely ruined our DNS or whatever and then gone to holiday :confused: )
But I will try (read: "do not expect anything soon" :wink: )

**Comment by oetiker** [comment] 2016-06-09 11:47
OR how about `equalityFunction` or `eqOverride` ... since `===` would return true ...

also regarding the format, I would expect to assign a function pointer, and in the generator, assign the function pointer to a static array in the Property generator class where it is assigned an id, so that it can be called directly from the gerated code ...

**Comment by oetiker** [comment] 2016-06-09 13:09
@schnepe2 just go to the appropriate file on github and click on the edit button (top right of the file) ... it is REALLY as simple as that ...

**Comment by schnepe2** [comment] 2016-06-09 14:47
@oetiker ...without having run it at least through the generator once? I would never do that :innocent:

Nevertheless I think some more tests are missing (like e.g. test whether the apply / transform calls are done as expected), but extending the tests should **never** be a problem.

> also regarding the format, I would expect to assign a function pointer, and in the generator, assign the function pointer to a static array in the Property generator class where it is assigned an id, so that it can be called directly from the generated code ... 

...no comprendo señor...

Feel free to change the code wherever you think it needs changes! Also I took the liberty to name the attribute "`comparator`", which might not be the optimal name...

**Comment by oetiker** [comment] 2016-06-09 14:59
@schnepe2 ignore me :) all is well

**Comment by level420** [comment] 2016-06-10 12:54
LGTM

**Comment by schnepe2** [comment] 2016-06-10 13:41
I have a general question regarding throwing the exception
(`qx.core.Property.js` around line 930):
 ```
else
{
  throw new Error( "Invalid type for 'comparator' attribute " +
                   "of property '" + name + "' in class '" + clazz.classname + "'" );
}
```
shouldn't this case be "guarded" by `qx.core.Environment.get("qx.debug")`? Like:
 ```
else if (qx.core.Environment.get("qx.debug"))
{
  throw new Error( "Invalid type for 'comparator' attribute " +
                   "of property '" + name + "' in class '" + clazz.classname + "'" );
}
```
I think it's enough to check only in source builds ("qx.debug").

The test-cases I've added to run through this code are _qx.core.Environment.get("qx.debug")_ guarded anyway :wink:

**Comment by level420** [comment] 2016-06-11 18:13
@schnepe2 I think it does not harm to have this also in the build version as It might be that an error situation was not detected during development and raises during production runs. Then it is valuable to have as that error bubbling up. I mean for those not having 100% code coverage in their code ;-)

**Comment by level420** [comment] 2016-06-14 07:41
Fixed with https://github.com/qooxdoo/qooxdoo/commit/05d65f0ab0bf0eee93b68881306448235e8d265e

**Closed by level420** 2016-06-14 07:41 UTC
Labels: enhancement

**Comment by schnepe2** [comment] 2016-06-14 08:02
Thanks!
As another 'gift': Here's my starting proposal for the missing API-Docs (sorry we forgot this):

```
 *   <tr><th>isEqual</th><td>Function, String</td><td>
 *     On setting of the property value the method of the specified name will
 *     be called to test if two values are equal. These checks for equality are
 *     performed by the Property-System to decide whether further actions (like
 *     e.g. calling applier methods or firing of events) are needed.
 *     The signature of the method is <code>function(valueA, valueB)</code>.
 *   </td></tr>
```

**Comment by level420** [comment] 2016-06-14 08:03
@schepe2 no problem! just create a PR for that ;-) Thank you.
