### ISSUE TITLE
testrunner in source version ommits silently tests for testfiles containing javascript syntax errors

### ISSUE THREAD

**Issue by level420** [qooxdoo/qooxdoo#9153] opened 2016-09-01 11:28 UTC
I found the bug in the qx.ui.basic.Atom test while fighting with testrunner source version and having console open. The syntax error occurred in the Atom.js testfile while the testrunner loaded each single testfile. Surprisingly the result was that the Atom.js file was not loaded at all and no tests where shown in the tree for qx.ui.basic.Atom (The Atom node was missing in the tests tree). I don't know but suspect that in this case the testrunner simply omitted all atom tests.

After the bug was in, there where no more tests executed for qx.ui.basic.Atom.

Not the entire test suite failed, but the all the tests in the file the syntax error was in. So syntax error in Atom.js -> no tests are executed from Atom.js

**Comment by level420** [comment] 2016-09-01 11:35
Surprisingly the tests ARE there in the build version and do not fail.

Here is the source code of the syntax error relevant test in qx.test.ui.basic.Atom
```javascript
    testSelectableSet : function('test') {
      var a = new qx.ui.basic.Atom();
      a.setSelectable(true);
      this.getRoot().add(a);
      this.flush();
      var l = a.getChildControl('label');	
      this.assertEquals("on", l.getContentElement().getDomElement().getAttribute("qxselectable"));
      a.destroy();
    },
```

**Comment by level420** [comment] 2016-09-01 11:40
The generator creates from the faulty function definition the following code:

```
testSelectableSet:function(b)
```
which turns the faulty into a correct syntax

**Comment by level420** [comment] 2016-09-01 12:13
it turns out that travis uses the karma testrunner which seems to also have this flaw.
Maybe @cajus and @peuter could have a look into this? Thank you.

**Comment by pcdummy** [comment] 2016-09-01 12:19
I don't know how, [here](https://github.com/qooxdoo/qooxdoo/blob/master/.travis/test-framework.sh#L13) we lint the Framework but not the tests, can't we lint tests files too there?

**Comment by cajus** [comment] 2016-09-01 12:27
I guess this can easily be fixed by changing the order of how karma/lint runs. If we run lint first and let karma only proceed, it would be OK.

**Comment by pcdummy** [comment] 2016-09-01 12:29
Lint runs first, but does it lint tests?

**Comment by level420** [comment] 2016-09-01 12:30
@cajus but then travis should have failed in the lint run, but it didn't

**Comment by cajus** [comment] 2016-09-01 12:31
What do I have to do to get the error locally?

**Comment by level420** [comment] 2016-09-01 12:34
git clone current master, then generate the source version of the testrunner and watch the console while testrunner is loading. You'll see a syntax error in Atom.js.
When the testrunner loaded completely go to the qx.ui.basic Testnode and find that there are not tests for  Atom.

**Comment by level420** [comment] 2016-09-01 12:38
The syntax error is in current master and therefore https://travis-ci.org/qooxdoo/qooxdoo/builds/156794341 which is the travis run for the last merge should normally fail because of the syntax error here: https://github.com/qooxdoo/qooxdoo/blob/master/framework/source/class/qx/test/ui/basic/Atom.js#L50
But it will not fail

**Comment by peuter** [comment] 2016-09-01 12:41
Well, the karma testrunner doesn't know about the test, because the syntax error prevents it from beeing loaded before the testrunner comes in place. I think the best and easiest way would be to use the linter first.

**Comment by cajus** [comment] 2016-09-01 12:53
@level420 it's all about `function(foo)` vs `function('foo')`?

**Comment by cajus** [comment] 2016-09-01 12:57
I guess there's "lint-test" is missing an `extend : ['lint']`  - *but*: lint does not detect that problem

**Comment by level420** [comment] 2016-09-01 13:08
I don't know the internals, but couldn't we make the karma testrunner fail if it fails to load one of the test files for any reason?

**Comment by cajus** [comment] 2016-09-01 13:15
karma uses qx internals to get the class. The problem is like in the browser: it does not load the atom class because of syntax errors.

I guess the easiest thing would be to fix the linter run find the issue and change the order of karma/lint.

**Comment by peuter** [comment] 2016-09-01 13:18
You can have a look at the sources here: https://github.com/qooxdoo/karma-qooxdoo/blob/master/qooxdoo-adapter.js#L151

**Comment by cajus** [comment] 2016-09-01 14:01
I've modified the linter to find these kind of issues. *BUT* we need to take care about *lint-test* to really execute what we want.

**Comment by cajus** [comment] 2016-09-01 14:11
Before this can be merged, the tests should be made lint clean. That is not the case currently.

**Comment by level420** [comment] 2016-09-01 14:42
As I understand before the karma qooxdoo adapter is running the tests, the source version of the testrunner constructed via 
```
./generate.py -sI test-source
```
in https://github.com/qooxdoo/qooxdoo/blob/master/.travis.yml#L28
and the karma qooxdoo adapter uses methods implemented by ```qx.dev.unit.TestSuite``` like ```getTestClasses```

**Comment by cajus** [comment] 2016-09-01 14:45
It will not load broken files. We need to lint first. But the linter does not detect the problem with out the PR.

**Comment by cajus** [comment] 2016-09-01 14:47
So basicaly one would want the linter to be able to find these kind of issues anyway. And we want the 'lint-test' job to work. I gree with you that this is just an indirect fix, but it is needed anyway.

**Comment by level420** [comment] 2016-09-01 14:49
OK. Then we need a braveheart who is willing to clean up the tests so they go through lint.
How do I start the linter locally?

**Comment by cajus** [comment] 2016-09-01 14:50
Just `./generate.py lint-test`. I'd do it, but the time before holidays is short. Some hours left...

**Comment by cajus** [comment] 2016-09-01 14:51
But you need to be in the PR to make that work of course.

**Comment by pcdummy** [comment] 2016-09-01 15:00
I'll do the test linting and cleanup this weekend.

**Comment by level420** [comment] 2016-09-01 15:06
great @pcdummy :+1:

**Comment by pcdummy** [comment] 2016-09-03 13:57
Lint done in #9158

**Comment by thron7** [comment] 2016-09-06 20:43
Re: build version works  -- This is due to string optimization. Turn off string optimization in the compile options, and the problem should also show up in build.

**Comment by level420** [comment] 2016-09-07 05:48
@thron7 for the travis integration we use the source buld of testrunner and the tests are not run by testrunner itself but by the qx karma adapter

**Comment by thron7** [comment] 2016-09-07 19:22
@level420 Sure, I just wanted to throw in this single piece of information why the same code works when optimized in build.

**Comment by hkollmann** [comment] 2019-12-17 18:26
@derrell : Test is working IMHO we can close the issue?

**Closed by hkollmann** 2019-12-17 18:26 UTC
Labels: bug
