### ISSUE TITLE
sometimes setShowCellFocusIndicator(false) will invalid

### ISSUE THREAD

**Issue by tiandian** [qooxdoo/qooxdoo#9280] opened 2017-01-29 22:15 UTC
after call Table.setShowCellFocusIndicator(false), 
when double click a editable cell to active the editing state, then use the ESC key  to escape the editing state, the Cell Focus Indicator will show, and then when use mouse single click or use the Up/Down key to select the other editable cell, the Cell Focus Indicator will still show too.

please see http://tinyurl.com/z2avss2

thanks!

**Comment by hkollmann** [comment] 2019-12-17 18:32
Can't reproduce - seems to be fixed in 5.0.2

**Closed by hkollmann** 2019-12-17 18:32 UTC
