### ISSUE TITLE
Microsoft Edge cancels the drag operation of a image

### ISSUE THREAD

**Issue by CosminCH** [qooxdoo/qooxdoo#9056] opened 2016-06-17 07:26 UTC
Hello,

We are having some problems with a drag and drop operation: there is one qx.ui.form.Button, which contains an image and a label; the button can be dragged (we have defined one drop target in our application).

Everything works fine under Chrome and Firefox, however Edge gives us a big problem: if the drag operation is initiated from the image of the button then there is a blur (I think native) event which occurs when the mouse gets out of the image (while still dragging), event which is handled in qx.event.handler.DragDrop by deleting the drag 'session'.

If the drag operation is initiated from the button's label or wherever outside the button's image we get the normal drag, dragover, etc events. I think those browsers do not fire the blur event.

I've been trying with many qooxdoo versions (3.5.1, 4.1, 5.0, 5.0.1), the behavior is the same: it works on Chrome and FF, but not on Edge.

Did somebody have a similar issue?

Thank you.

**Comment by johnspackman** [comment] 2016-06-17 07:32
Hi

Please can you try and reproduce this with a playground example?  The playground is here:  

	http://demo.qooxdoo.org/current/playground/#Hello%20World-ria

Thanks
John

On 17 June 2016 at 08:40:42, CosminCH (notifications@github.com) wrote:

Hello,

We are having some problems with a drag and drop operation: there is one qx.ui.form.Button, which contains an image and a label; the button can be dragged (we have defined one drop target in our application).

Everything works fine under Chrome and Firefox, however Edge gives us a big problem: if the drag operation is initiated from the image of the button then there is a blur (I think native) event which occurs when the mouse gets out of the image (while still dragging), event which is handled in qx.event.handler.DragDrop by deleting the drag 'session'.

If the drag operation is initiated from the button's label or wherever outside the button's image we get the normal drag, dragover, etc events. I think those browsers do not fire the blur event.

I've been trying with many qooxdoo versions (3.5.1, 4.1, 5.0, 5.0.1), the behavior is the same: it works on Chrome and FF, but not on Edge.

Did somebody have a similar issue?

Thank you.

**Comment by johnspackman** [comment] 2016-06-17 07:38
PS there is a version of the playground with the latest code here:

	http://qooxdoo.github.io/devel/playground/#Hello%20World-ria



On 17 June 2016 at 08:45:32, John Spackman (john.spackman@zenesis.com) wrote:

Hi

Please can you try and reproduce this with a playground example?  The playground is here:  

http://demo.qooxdoo.org/current/playground/#Hello%20World-ria

Thanks
John

On 17 June 2016 at 08:40:42, CosminCH (notifications@github.com) wrote:

Hello,

We are having some problems with a drag and drop operation: there is one qx.ui.form.Button, which contains an image and a label; the button can be dragged (we have defined one drop target in our application).

Everything works fine under Chrome and Firefox, however Edge gives us a big problem: if the drag operation is initiated from the image of the button then there is a blur (I think native) event which occurs when the mouse gets out of the image (while still dragging), event which is handled in qx.event.handler.DragDrop by deleting the drag 'session'.

If the drag operation is initiated from the button's label or wherever outside the button's image we get the normal drag, dragover, etc events. I think those browsers do not fire the blur event.

I've been trying with many qooxdoo versions (3.5.1, 4.1, 5.0, 5.0.1), the behavior is the same: it works on Chrome and FF, but not on Edge.

Did somebody have a similar issue?

Thank you.

**Comment by CosminCH** [comment] 2016-06-17 07:58
No, I cannot reproduce it in playground, that's why I asked if there is somebody which had similar issues.

The playground was not able to parse the shorten url, so I paste the reduced code I have tried there.

qx.Class.define("webui.ui.form.PXButton", {
	extend : qx.ui.form.Button,

	construct : function(label, icon, command) {
		this.base(arguments, label, icon, command);
		this.setIconPosition("top");
		this.applySupportDrag();
	},

	members : {
		_dragFeedback : null,
		_isDragging : false,

		/**
		 * Initializes the drag feedback. The default widget is a semi-transparent
		 * {@link qx.ui.basic.Image} using the icon of the button as source but subclasses may
		 * create their own feedback widget
		 */
		_createDragFeedback : function() {
			var dragFeedback = new qx.ui.basic.Image();
			dragFeedback.setOpacity(0.5);
			dragFeedback.setZIndex(500);
			dragFeedback.addState("selected");
			dragFeedback.setLayoutProperties({
				left : -1000,
				top : -1000
			});
			qx.core.Init.getApplication().getRoot().add(dragFeedback);
			return dragFeedback;
		},

		/**
		 * Applies the {@link #supportDrag} property
		 * 
		 * @param newValue
		 *            {Boolean} New value
		 * @param oldValue
		 *            {Boolean ? false} Old value
		 */
		applySupportDrag : function() {
			
				if (this._dragFeedback === null) {
					this._dragFeedback = this._createDragFeedback();
					this.addListener("dragstart", this.__onDragStart, this);
					this.addListener("drag", this.__onDrag, this);
					this.addListener("dragend", this.__onDragEnd, this);
				}

				var cursor = qx.core.Environment.select("engine.name", {
					"gecko" : '-moz-grab',
					"webkit" : '-webkit-grab',
					"default" : 'url(' + qx.util.ResourceManager.getInstance().toUri('webui/cursor/openhand.cur')
							+ '), default !important'
				});
				this.setCursor(cursor);
				this.setDraggable(true);
		},

		// overwrite qx.ui.form.Button#_onMouseDown
		_onPointerDown : function(e) {
			if (!e.isLeftPressed()) {
				return;
			}

			this.removeState("abandoned");
			this.addState("pressed");
		},

		_actionFailedCallback : function(ev) {
			var result = ev.getTarget().getResponse();

			if (result === null) {
				result = "Unable to execute the topic action!";
			}

			console.debug(result);
		},

		__onDragStart : function(e) {
			this._isDragging = true;
			e.addAction("copy");
			var item = e.getTarget();
			this._dragFeedback.set({
				source : item.getIcon(),
				width : item.getChildControl("icon").getBounds().width,
				height : item.getChildControl("icon").getBounds().height
			});
		},

		__onDragEnd : function(e) {
			this._isDragging = false;
			this.removeState("dragover");
			this._dragFeedback.setDomPosition(-1000, -1000);
		},

		__onDrag : function(e) {
			this._isDragging = true;
			this.removeState("dragover");
			var height = this._dragFeedback.getHeight();
			this._dragFeedback.setDomPosition(e.getDocumentLeft() + 5, e.getDocumentTop() - height - 5);
		}
	}
});


// Create a button
var button1 = new webui.ui.form.PXButton("First Button", "icon/22/apps/internet-web-browser.png");


// Document is the application root
var doc = this.getRoot();

// Add button to document at fixed coordinates
doc.add(button1,
{
  left : 100,
  top  : 50
});


I see in the playground that the drag operation is not started while the pointer is inside the image (as it happens in our application), that's the difference in my opinion.

**Comment by CosminCH** [comment] 2016-06-17 08:24
The img I mentioned before is something like 
img style="left: 45px; top: 3px; width: 16px; height: 16px; position: absolute; z-index: 10; overflow-x: hidden; overflow-y: hidden; box-sizing: border-box;" src="http://localhost:8080/resources/arm.png" qxSelectable="off"

The div in the playground
div style='background-position: 0px 0px; left: 33px; top: 3px; width: 22px; height: 22px; background-image: url("resource/qx/icon/Tango/22/apps/internet-web-browser.png"); background-repeat: no-repeat; position: absolute; z-index: 10; overflow-x: hidden; overflow-y: hidden; box-sizing: border-box; -ms-user-select: none; -ms-touch-action: none; touch-action: none;' qxClass="qx.ui.basic.Image" qxSelectable="off" qxanonymous="true"

**Comment by cajus** [comment] 2016-06-17 08:37
Does your problem reproduce with *source* and *build* or just with one of them?

**Comment by level420** [comment] 2016-06-17 09:03
@CosminCH are you shure that your derive the dragable button in your app directly from qx.ui.form.Button?

**Comment by level420** [comment] 2016-06-17 09:20
Some Ideas: if the drag and drop logic does some special handling for different browsers, then it may be that it needs to be also done for edge e.g. via 

```javascript
 if (qx.core.Environment.get("browser.name") == "edge")
```
as edge is not reported as mshtml.

I remember the fix https://github.com/qooxdoo/qooxdoo/commit/53e11fda354d39642abe960d4f039649cf87f1bf for issue https://github.com/qooxdoo/qooxdoo/issues/8904

**Comment by CosminCH** [comment] 2016-06-17 10:00
Thank you very much for your answers!

I have found the issue: the qx.ui.basic.Image is creating the img element if the image's scale mode is not 'alphaScaled' and not 'nonScaled'; I think this img element is not properly handled in the drag and drop code.

The solution for my particular case is to force one of the two modes. The div is created for Edge as well and the drag and drop is working.

**Comment by level420** [comment] 2016-06-17 10:49
It's odd that the @CosminCH ist giving up on this, as it may be that we have a bug which is based on what I wrote, e.g. the logic has to be adapted to the edge browser (vs. mshtml).
Reopening

**Comment by level420** [comment] 2016-06-17 10:56
@CosminCH what were the exact steps to reproduce this? How did you set the image scale mode exacltly?

**Comment by level420** [comment] 2016-06-17 11:00
The playground code given does not trigger the bug. The button has to be created in a special way.

**Comment by level420** [comment] 2016-06-17 11:08
Edge is reporting itself as engine webkit via ```qx.core.Environment.get("engine.name")```

**Comment by CosminCH** [comment] 2016-06-17 11:09
Try this code:

`qx.Class.define("webui.ui.form.PXButton", {
	extend : qx.ui.form.Button,

	construct : function(label, icon, command) {
		this.base(arguments, label, icon, command);
		this.setIconPosition("top");
		this.applySupportDrag();
		this.getChildControl("icon").setScale(true);
	},

	members : {
		_dragFeedback : null,
		_isDragging : false,

		/**
		 * Initializes the drag feedback. The default widget is a semi-transparent
		 * {@link qx.ui.basic.Image} using the icon of the button as source but subclasses may
		 * create their own feedback widget
		 */
		_createDragFeedback : function() {
			var dragFeedback = new qx.ui.basic.Image();
			dragFeedback.setOpacity(0.5);
			dragFeedback.setZIndex(500);
			dragFeedback.addState("selected");
			dragFeedback.setLayoutProperties({
				left : -1000,
				top : -1000
			});
			qx.core.Init.getApplication().getRoot().add(dragFeedback);
			return dragFeedback;
		},

		/**
		 * Applies the {@link #supportDrag} property
		 * 
		 * @param newValue
		 *            {Boolean} New value
		 * @param oldValue
		 *            {Boolean ? false} Old value
		 */
		applySupportDrag : function() {
			
				if (this._dragFeedback === null) {
					this._dragFeedback = this._createDragFeedback();
					this.addListener("dragstart", this.__onDragStart, this);
					this.addListener("drag", this.__onDrag, this);
					this.addListener("dragend", this.__onDragEnd, this);
				}

				var cursor = qx.core.Environment.select("engine.name", {
					"gecko" : '-moz-grab',
					"webkit" : '-webkit-grab',
					"default" : 'url(' + qx.util.ResourceManager.getInstance().toUri('webui/cursor/openhand.cur')
							+ '), default !important'
				});
				this.setCursor(cursor);
				this.setDraggable(true);
		},

		// overwrite qx.ui.form.Button#_onMouseDown
		_onPointerDown : function(e) {
			if (!e.isLeftPressed()) {
				return;
			}

			this.removeState("abandoned");
			this.addState("pressed");
		},

		_actionFailedCallback : function(ev) {
			var result = ev.getTarget().getResponse();

			if (result === null) {
				result = "Unable to execute the topic action!";
			}

			console.debug(result);
		},

		__onDragStart : function(e) {
			this._isDragging = true;
			e.addAction("copy");
			var item = e.getTarget();
			this._dragFeedback.set({
				source : item.getIcon(),
				width : item.getChildControl("icon").getBounds().width,
				height : item.getChildControl("icon").getBounds().height
			});
		},

		__onDragEnd : function(e) {
			this._isDragging = false;
			this.removeState("dragover");
			this._dragFeedback.setDomPosition(-1000, -1000);
		},

		__onDrag : function(e) {
			this._isDragging = true;
			this.removeState("dragover");
			var height = this._dragFeedback.getHeight();
			this._dragFeedback.setDomPosition(e.getDocumentLeft() + 5, e.getDocumentTop() - height - 5);
		}
	}
});


// Create a button
var button1 = new webui.ui.form.PXButton("First Button", "icon/22/apps/internet-web-browser.png");


// Document is the application root
var doc = this.getRoot();

// Add button to document at fixed coordinates
doc.add(button1,
{
  left : 100,
  top  : 50
});

`

The difference is the call this.getChildControl("icon").setScale(true);

What you will see in Edge is that dragging the image is different than dragging the rest of the button.

(Unrelated to this bug: the devel playground cannot even parse the code above in my Edge installation. Please use the current playground).

**Comment by CosminCH** [comment] 2016-06-17 11:10
@level420 and the User Agent String is

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2486.0 Safari/537.36 Edge/13.10586

which is.. a bit strange.

**Comment by level420** [comment] 2016-06-17 11:29
I'm currently unable to run the example in my local playground on edge. I'm getting the error URL is to long :-(

**Comment by CosminCH** [comment] 2016-06-17 11:36
http://demo.qooxdoo.org/current/playground/#Hello%20World-ria 
works for me, if it's of any help.

**Comment by level420** [comment] 2016-06-17 11:37
Tricked the playground to work by removing all unneeded whitespace and comments from the example code

**Comment by level420** [comment] 2016-06-17 12:09
I've did some tests, but could not find anything that is caused by paths being taken because Edge reports to be ```engine.name == 'webkit'```.
But I'm not shure to have inspected everyhing nor did I search for other causes for this.

**Comment by level420** [comment] 2016-12-01 16:11
Closing this for now. 
Please reopen if appropriate

**Closed by level420** 2016-12-01 16:11 UTC
Labels: bug, bug confirmed
