### ISSUE TITLE
Unable to add native Objects in qx.util.fsm.FiniteStateMachine

### ISSUE THREAD

**Issue by RemiHeugue** [qooxdoo/qooxdoo#9290] opened 2017-02-14 14:33 UTC
The documentation states that we can call [qx.util.fsm.FiniteStateMachine#addObject](http://www.qooxdoo.org/devel/api/#qx.util.fsm.FiniteStateMachine~addObject!method_public) with a native object which is impossible because internally it call [obj.toHashCode()](https://github.com/qooxdoo/qooxdoo/blob/69cf8b0/framework/source/class/qx/util/fsm/FiniteStateMachine.js#L376) which doesn't exists on native objects.

Should we change the documentation or replace the call to
`obj.toHashCode()`
by
`qx.core.ObjectRegistry.toHashCode(obj)`
which work on native objects too (it automatically add the $$hash property if it's not present) ?

**Comment by derrell** [comment] 2017-02-14 14:54
I think two things are wrong here. Firstly, there was never any intention that a _native_ object be stored there. As opposed to "typically a widget" would be something that descends from `qx.core.Object`. So the documentation should be changed to say that the `obj` parameter is type `qx.core.Object`.

Given the above, it used to work. The recent changes to not have all objects have hash codes in the registry by default has broken it. We should be able to `qx.core.ObjectRegistry.toHashCode()` for this, with the current implementation.

Feel free to provide a PR. If you don't want to, I'll work on it, but may not get to it for a few weeks.

Thanks for reporting!

**Comment by RemiHeugue** [comment] 2017-02-14 15:12
I'm not sure I understand well.
It still work correctly with qx.core.Object because while they aren't stored in the ObjectRegistry anymore, they still have a hash code, which is generated by the ObjectRegistry. There is no problem here.

ObjectRegistry.toHashCode doesn't, and has never registered objects into the registry. What I was trying to say is that since we can use this on native objects to give them a unique hash (without adding them to the registry), we could use it to support named native objects inside FiniteStateMachine.

But I would totally understand that this isn't the intended behavior. :)

**Comment by derrell** [comment] 2017-02-14 15:17
Correct. It was never an intended behavior to support native objects there, so in any case, the documentation should be corrected so it says that `obj` is `qx.core.Object`. Then again, if you have a need for native objects to be supported there, and want to provide a PR that makes that possible, I'm open to it.

**Comment by level420** [comment] 2017-02-20 13:59
Fixed via https://github.com/qooxdoo/qooxdoo/pull/9291

**Closed by level420** 2017-02-20 13:59 UTC
