### ISSUE TITLE
Several issues when closing Window widget by ESC key (BZ#9208)


### ISSUE THREAD

**Issue by qx-bug-importer** [qooxdoo/qooxdoo#8936] opened 2015-09-14 09:42 UTC
_Joseph Karras (stylkarr) wrote:_

The problem is harder to describe than see in action, so here is a playground application that demonstrates it:

http://tinyurl.com/nsszdt6

1st bug: Click the button to open the window, hover the hover area and press ESC on your keyboard -&gt; an exception is thrown

2nd bug: Click the button to open the window, hover your mouse over the edge of the window to change the cursor to its resize variant, press ESC on your keyboard -&gt; cursor is not reset

**Comment by level420** [comment] 2016-09-12 07:01
Reopened due to user request.

**Comment by level420** [comment] 2016-09-12 07:17
@JosKar I'm able to reproduce the second bug, but not the first one. Maybe because I can't understand what is meant by "hover the hover area".
Could you please re evaluate and report back here? Thank you!

**Comment by JosKar** [comment] 2016-09-12 14:26
Hi @level420 
I just re evaluate the playground code in FF ESR 45.3.0 and Chromium  52.0. I got the same results.
Steps to reproduce the first bug:
1) Click the button click me. A window should appear.
2) Hover your mouse over the label "Hover me and press ESC". A pop up should  appear.
3) With the pop up opened press the ESC key to close the window.

In your browser console you will see the following error:
> qx.ui.core.queue.Layout: Error in the 'Layout' queue:TypeError: Cannot read property 'setStyles' of null TypeError: Cannot read property 'setStyles' of null

**Comment by level420** [comment] 2016-11-11 14:38
It might be that the 1st issue in the description was fixed by PR https://github.com/qooxdoo/qooxdoo/pull/168

**Comment by level420** [comment] 2016-11-15 13:13
Fixed in master via https://github.com/qooxdoo/qooxdoo/pull/9173 and https://github.com/qooxdoo/qooxdoo/pull/168

**Closed by level420** 2016-11-15 13:13 UTC
Labels: bug, C:desktop.layout
