### ISSUE TITLE
Qooxdoo images are not loaded in IE when app is served in https and base URL is set

### ISSUE THREAD

**Issue by ronkie** [qooxdoo/qooxdoo#9353] opened 2017-07-05 12:02 UTC
We have a qooxdoo app that is served by Tomcat via https and with base URL set in index.html, so all the resources are served from a different location than index.html location.

There is a Checkbox widget on a page that appears not checked when it actually is. We discovered that it was because chekbox image was not loaded (error 404).
Other images we have in the app are loaded correctly.

There is an issue:
https://github.com/qooxdoo/qooxdoo/issues/2564

Code that was added for it adds a prefix for the url to make it absolute, but it does not take into account "base" url, so app tries to load images from the same location as index.html resides.

**Comment by ronkie** [comment] 2017-07-05 12:19
![image not found ie](https://user-images.githubusercontent.com/6853101/27863986-f1c51610-618c-11e7-883b-c1ab3031fa21.png)

**Comment by level420** [comment] 2017-07-26 09:40
Fixed via https://github.com/qooxdoo/qooxdoo/pull/9354

**Comment by derrell** [comment] 2017-10-24 11:38
Unfortunately, this change breaks existing code. The class `qx.util.ResourceManager` is used in non-GUI code, where `document` does not exist. We need to find a different way of solving the original problem, or ensure that this code still works in non-GUI environments.

**Comment by derrell** [comment] 2017-10-24 12:18
I've tracked this down further. The problem is that the patch puts a dependency in `qx.util.ResourceManager` on `qx.bom.Selector`  which brings in the Sizzle library that tries to do a bunch of stuff at initialization time that assumes a GUI environment. There can not be a dependency on `qx.bom.Selector` in `qx.util.ResourceManager`.

**Comment by level420** [comment] 2017-10-24 12:30
OK then the faulty line is https://github.com/qooxdoo/qooxdoo/blob/master/framework/source/class/qx/util/ResourceManager.js#L288

**Comment by derrell** [comment] 2017-10-24 12:34
Correct, but the whole patch appears to depend on that...

**Comment by ronkie** [comment] 2017-10-24 12:41
Hi guys,

I've used qxWeb at first, but that was also not good?

https://github.com/ronkie/qooxdoo/commit/167eb14e769ee70b6fd5995e151a3dd9fcab67fc

Maybe we could simply use

document.querySelectorAll("base")

But before checking for the document, if it is there....

**Comment by level420** [comment] 2017-10-25 06:48
@ronkie could you please verify if the solution in PR https://github.com/qooxdoo/qooxdoo/pull/9415 works for you? Thank you!

**Closed** 2019-04-17 09:31 UTC
