### ISSUE TITLE
qx.util.format.DateFormat: auto jumping to next year value for dates 31/12/2018, 30/12/2019 & 31/12/2019

### ISSUE THREAD

**Issue by paragasu** [qooxdoo/qooxdoo#9274] opened 2017-01-23 05:18 UTC
How to reproduce
1. Go to http://tinyurl.com/grmt4j2
2. Select the date 30/12/2019 or 31/12/2019
3. Expected value is 30/12/2019 or 31/12/2019 but the value shown on the text field automatically become 30/12/2020 or 31/12/2020.

Another similar date that trigger the issue is 31/12/2018. The value will auto change to 31/12/2019.
So far only this 3 date - 31/12/2018, 30/12/2019 & 31/12/2019 has this bug on google chrome.

Tested effected browser google chrome v55.0.2883.87 64bit & v56.0.2924.21 beta 64bit

**Comment by level420** [comment] 2017-01-23 08:21
This issue is not limited to chrome. It's also present on firefox 51, internet explorer 11 and opera 42 (tested on windows7).
The simpliest code to reproduce is:
```javascript
var df = new qx.ui.form.DateFormat("dd/MM/YYYY");
var date = new Date("2019-12-31");
console.log(df.format(date));
```

**Comment by level420** [comment] 2017-01-23 08:29
Another observation: the issue seems to be only present for the years 2018 and 2019, as @paragasu reported.

**Comment by level420** [comment] 2017-01-23 09:23
After staring a long time to the code, I finally got the solution:

This is not a bug, it works like intended as the format `YYYY` (uppercase y) retreives the "week year".

The correct format would be `yyyy` (lowercase y) which works as expected.

See the corrected playground sample:

http://tinyurl.com/ztmg6xs

Closing as invalid.

**Closed by level420** 2017-01-23 09:23 UTC
Labels: bug, bug confirmed

**Comment by level420** [comment] 2017-01-23 09:31
See api documentation:
http://www.qooxdoo.org/devel/api/#qx.util.format.DateFormat
https://en.wikipedia.org/wiki/ISO_week_date

PHP-Related, but a good explanation 
https://derickrethans.nl/iso-8601-weeks.html
