### ISSUE TITLE
Table focus indicator offset

### ISSUE THREAD

**Issue by adrelino** [qooxdoo/qooxdoo#10380] opened 2022-03-10 12:20 UTC
**Describe the bug**
Sometimes there is an offset between the table cell focus indicator and the row selection.

**To Reproduce**
1. Go to https://qooxdoo.org/qxl.playground/#Table-ria
2. Select a table row with ID >= 10.
3. Change the zoom level  (Ctrl+Mousewheel while mouse is outside of table)
   *  Chrome:
       - 50%: large offset (one row width) above, decreasing linearly when choosing 67%, 75%, 80%, 90%.
       - 110%, 125%: slight offset below, but 150% 175%, 200% and larger seems to work
   * Firefox:
       - **100%: @marcelr even reports an offset with the default zoom level on his desktop (debian, 4k resolution), see screenshot below, althouh I could not reproduce this on my machine (ubuntu, WQHD resolution).**
       - all other zoom levels: linearly changing offset above/below the row while changing zoom levels.

**Expected behavior**
No offset between table row selection and cell focus indicator frame.

**Screenshots**
![418aa813-0daf-4af7-93f3-593eef27a05f](https://user-images.githubusercontent.com/6432001/157659501-915bebf7-fe52-4236-b645-e4c3015cfb1b.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu, Debian
 - Browser: Chrome, Firefox
 - Version: 97 (both browsers)

**Comment by zaucker** [comment] 2022-03-10 12:52
- Can reproduce the behavior described above with Ubuntu 20.04, Chrome 99.0.4844.51
- Problem does not occur on a MacBook Pro, macOS 12.2.1, same Chrome version

**Comment by zaucker** [comment] 2022-03-10 13:23
![FokusOffset](https://user-images.githubusercontent.com/198038/157670503-20d3a430-a791-4efe-a738-2de27f81aba9.png)
This shows the offset a bit better with the row being deselected.

**Comment by oetiker** [comment] 2022-03-11 07:19
I could reproduce the phaenomenon on firefox 97 on linux ... very odd ... somehow as if it was some rounding error

**Comment by goldim** [comment] 2023-04-05 08:12
Duplicate of #10505

**Closed** 2024-05-13 20:40 UTC
