### ISSUE TITLE
v5: SelectBox does not make any search in FireFox

### ISSUE THREAD

**Issue by RayIslas** [qooxdoo/qooxdoo#10114] opened 2021-02-02 19:12 UTC
**Describe the bug**
While typing any text SelectBox does not make any search in FF

**To Reproduce**
// Create a SelectBox
var selBx = new qx.ui.form.SelectBox();
var i;

[
  "abracadabra",
  "bruhaha",
  "chick filet",
  "delta"
].forEach(
  (word) => 
  {
    var itm = new qx.ui.form.ListItem(word);
    selBx.add( itm )
  });

// Document is the application root
var doc = this.getRoot();

// Add button to document at fixed coordinates
doc.add(selBx,
{
  left : 100,
  top  : 50
});

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro
 - Browser -FireFox 
 - Version 80 64bits

**Smartphone (please complete the following information):**

**Additional context**
Derrell made a playground and test it, and it didn't work.

**Comment by oetiker** [comment] 2021-02-03 10:04
might this be a regression from #10077 ? @zaucker ?

**Comment by hkollmann** [comment] 2021-02-03 10:14
from gitter:
Christian Boulanger @cboulanger Feb. 02 20:51
Ok, this means that the FF bug has been fixed in master, and is going to be released in v6. Since we won't do any mor 5.0.x releases, this means that you need to a) either upgrade to v6, which is mostly painless (recommended), or b) identify the commit that fixed it, and manually integrate it to your v5 sources (probably a nightmare).
V6 (the current master) is almost fully BC, i.e. it supports working with the generator. Although be advised that this support will be dropped in the next version, so now is a good time to migrate your app to use the shiny new Compiler https://qooxdoo.org/documentation/#/development/compiler/migration
RayIslas @RayIslas Feb. 02 23:28
@cboulanger Ok, in the meantime I'll try option b) Because I begun to study v6 since a few days ago to migrate my app to v6
Thanks a lot all of you :)
_

**Comment by hkollmann** [comment] 2021-02-03 10:14
It's a v5 problem.

**Comment by zaucker** [comment] 2021-02-03 10:25
> might this be a regression from #10077 ? @zaucker ?

No, I didn't touch `SelectBox`, just `VirtualSelectBox`.

**Comment by cboulanger** [comment] 2021-02-05 07:26
Closing as "wontfix", since this is a v5 issue. Solution is to upgrade to v6 or patch relevant code (probably related to key event handling) with v6 code.

**Closed by cboulanger** 2021-02-05 07:26 UTC
